# Generated by Django 6.0.3 on 2026-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Josiah Pharmacy and Stores', max_length=255)),
                ('location', models.CharField(default="St. Mary's", max_length=255)),
            ],
        ),
    ]
