# Generated by Django 6.0.3 on 2026-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescribing_doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
